services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI_USERS}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - ecommerce-network
    replicas: 2

  shopping-cart-service:
    build: ./shopping-cart-service
    ports:
      - "5005:5005"
    environment:
      - MONGO_URI=${MONGO_URI_CART}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - ecommerce-network
    replicas: 2

  product-service:
    build: ./product-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${MONGO_URI_PRODUCTS}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - ecommerce-network
    replicas: 2

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=${MONGO_URI_ORDER}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - ecommerce-network
    replicas: 2
  
  payment-service:
    build: ./payment-service
    ports:
      - "5002:5002"
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - MONGO_URI=${MONGO_URI_PAYMENT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - ecommerce-network
    replicas: 2
    
  notification-service:
    build: ./notification-service
    ports:
      - "5004:5004"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - ecommerce-network
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ecommerce-network
    depends_on:
      - user-service
      - product-service
      - shopping-cart-service
      - order-service
      - payment-service

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce-network

volumes:
  mongo-data:

networks:
  ecommerce-network:
    driver: bridge